### PR TITLE
Add matching directory hierarchies for the Components and Style folders

### LINKED ISSUE #54: [Internal] Hierarchical Directories for Components
# Overview of Proposed Changes
We should add hierarchical directories for the components to remove any issues that arise from identical naming and also to prevent all components being dumped in the same folder. This will allow for a better organisation structure that will be easier to maintain in the future.

# Details
Highest Level Folders in the Components directory should refer to different pages, and subsequent component hierarchy should be represented in sub-folders as needed.

### PR DESCRIPTION
**Pull request by AvengingPrime**
Closes #54. Added a base for a hierarchical directory structure for the components and style folders. This helps better organise the files for later work, and also mitigates any duplicate component naming issues.

### CODE REVIEW

**Comment by WillieCubed** [comment]
Just wanted to verify: is this ready for review? If not, you can mark it as a draft until you're ready.

image

**Comment by AvengingPrime** [comment]
> Just wanted to verify: is this ready for review? If not, you can mark it as a dra

I think so. For now, I've just added higher level directories. As for sub-directories related to different components (i.e. sub directories for the Sidebar and Content Viewer Components in the Content Viewer Page), they will be added by the respective issue's assignee in the actual issue branch. For example, after this gets merged, I'll add the Content Viewer's sub-directories in the content viewer issue.

**Comment by WillieCubed** [comment]
I currently only see a single commit with a single new file. If you've created empty directories, they won't show in Git because Git only tracks files. If you would like to go ahead and move the components to use the new directory structure, I would wait until after #40 is merged, merge those changes into this branch, and then refactor from there and leave this as a draft PR until those components are ready.

Additionally, I would keep custom styles (the ones not using Tailwind CSS) in [CSS modules](https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css) that are within a component's subdirectory and refrain from using global styles.

**Comment by WillieCubed** [comment]
Closing as stale.

**Pull request closed without merging**
